#!/bin/bash



uptime | awk -F"up " '{print $2}' | awk -F, '{print "Uptime: " $1 " &" $2 " hours"}'
uptime | awk '{print "CPU Load Average: " $(NF-2) $(NF-1)  $NF}'

if command -v free >/dev/null 2>&1;then
	free | awk '/Mem:/ {print "Free Ram: " $4 " MB"}'
	free | awk '/Swap:/ {print "Swap Used: " $3 " MB"}'
else
	top | awk '/Mem:/ {print $0}' | awk -F, '{print "Free Ram: " $5}'
	top | awk '/Swap:/ {print $0}' | awk -F, '{print "Swap Used: " $2}' 	
fi


echo -e "\nInterface Address"



if command -v ip >/dev/null 2>&1; then
	ip -br addr | awk '{print $1 " " $3}'
elif command -v ifconfig >/dev/null 2>&1; then
	ifconfig | awk '/inet / {print $1 " " $2}'
fi



if ping -c 1 -W 5 8.8.8.8 &> /dev/null; then
	echo "Internet Connectivity: Yes"
else
	echo "Internet Connectivity: No"
fi



echo -e "\nUser Accounts"
wc -l /etc/passwd | awk '{print "Total Users: " $1}'
grep "/bin/bash" /etc/passwd | wc -l | awk '{print "Active Users: " $1}'



echo -e "\nShells          Users"
awk -F: '{print $NF}' /etc/passwd | sort | uniq -c | awk '{print $2 "          " $1}'



echo -e "\nFilesystem /boot"
find /boot -type d | wc -l | awk '{print "Number of directories in /boot: " $1}'
find /boot -type f | wc -l | awk '{print "Number of files in /boot: " $1}'
find /boot -type l | wc -l | awk '{print "Number of symbolic links in /boot: " $1}'
